# Generated by Django 4.1.7 on 2023-03-19 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_objective', models.CharField(max_length=2000)),
                ('activity_date', models.DateTimeField(verbose_name='date published')),
                ('activity_owner', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='home_function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_prioritized', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_activities.activity')),
            ],
        ),
    ]
