# Generated by Django 4.1.7 on 2023-03-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_function',
            new_name='HomeFunction',
        ),
    ]
